#!/usr/bin/python2.7

from Crypto.Cipher import AES
from Crypto.Hash import MD5

x = AES.new('keyquest',AES.MODE_ECB)
pt = ("I am the very model of a modern major general.")
while len(pt)%8 != 0: pt += "X"
ct = x.encrypt(pt)
print(len(ct))
#x.decrypt(ct)

#x.encrypt(pt)
